### ISSUE TITLE
Question about Language Support

### ISSUE THREAD

**Issue by ecoulson** [ZhengC1/PenisParser#27]
Hey so in the readme I think that we might have missed a key point of this project. This being that penis is only translated and replaced in English. I feel that it is important to be inclusive towards all cultures so they can see the pinnacle of technology that we are achieving here with penis parser.

**Comment by reverendrainwater** [comment]
I support this motion. The PenisParser needs to support more languages (not programming, but spoken languages). I vote the first languages to be supported as Inuit, Esperanto, and Swahili.

**Comment by ecoulson** [comment]
Hey so I found a free API for translation called translatr. Also I can create a restful API for the sole purpose of storing translation and slang of the word penis. I have an implementation of translatr in node js that I will push up when I return home.
