### ISSUE TITLE
Not every implementation has a README

### ISSUE THREAD

**Issue by reverendrainwater** [ZhengC1/PenisParser#44]
Some of the implementations do not have READMEs.

These need to be added. 

Any new pulls without a README will be rejected until a README is added. 

Don't be braindead, document your shit.

**Comment by Frederik-Baetens** [comment]
I like that this is turning into a serious project with documentation.

Next up: unit tests :p

**Comment by ZhengC1** [comment]
why would they need a README? it's not complicated enough to warrant this.

**Comment by DV8FromTheWorld** [comment]
Agreed. Each individual implementation does not need a README.

**Comment by reverendrainwater** [comment]
But that's the joke, it's a poke at the people who insist on documenting absolutely everything.

**Comment by ransomts** [comment]
Poe's law though

**Comment by reverendrainwater** [comment]
smurfendrek123 seemed to get it but I guess I should be more verbose in the future.
